sf_filebase_directory:
  class: sfDoctrineRouteCollection
  options:
    model:                sfFilebaseDirectory
    module:               sf_filebase_directory
    prefix_path:          sf_filebase_directory
    column:               id
    with_wildcard_routes: true

sf_filebase_file:
  class: sfDoctrineRouteCollection
  options:
    model:                sfFilebaseFile
    module:               sf_filebase_file
    prefix_path:          sf_filebase_file
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: start, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
